# Generated by Django 4.1.7 on 2023-03-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
