# Generated by Django 4.1.7 on 2023-03-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
