# Generated by Django 4.1.7 on 2023-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emo_create", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="이미지가 저장되는 디렉토리")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="img",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="img",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
