# Generated by Django 4.1.7 on 2023-08-25 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emo_create", "0003_alter_cameraimage_id_alter_cameraimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="StyledImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image_path", models.CharField(max_length=255)),
                ("styled_image_path", models.CharField(max_length=255)),
                ("chosen_style", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
