# Generated by Django 4.1.6 on 2023-03-15 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_board_delete_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="board", name="writer",),
        migrations.AddField(
            model_name="board",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
