# Generated by Django 4.1.6 on 2023-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_photo_delete_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="imgfile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
