# Generated by Django 4.1.6 on 2023-04-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="room", options={"ordering": ["-pk"]},),
    ]
