# Generated by Django 4.1.7 on 2023-06-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-pk"]},
        ),
    ]
